# Generated by Django 3.2.4 on 2021-06-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='content',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='title',
        ),
        migrations.AddField(
            model_name='entry',
            name='Age',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Bordetella',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Breed',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Cell',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Color',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='DHLPP',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Dosage',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='EVE',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Emer',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Ends',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='First_Name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='GCD',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Groomer',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Home',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Last_Name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Meds',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Mrn',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Name_of_animal',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Our_or_own_food',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Rabies',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Remarks',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Rot',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Sex',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Starts',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Type_of_animal',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Vet',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Weight',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Work',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
