# Generated by Django 3.2.4 on 2021-06-08 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_entry_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_groom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='date_in',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='date_out',
            field=models.DateTimeField(null=True),
        ),
    ]
