# Generated by Django 3.2.4 on 2021-06-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0009_entry_kennel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='Remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
