# Generated by Django 3.2.4 on 2021-06-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0010_alter_entry_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='Food_Location',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
