# Generated by Django 3.2.4 on 2021-06-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0011_entry_food_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='Kennel',
            field=models.CharField(blank=True, choices=[('K1', 'K1'), ('K2', 'K2'), ('K3', 'K3')], max_length=40, null=True),
        ),
    ]
