# Generated by Django 3.2.4 on 2021-06-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0013_auto_20210614_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='Checked_in',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=25, null=True),
        ),
    ]
